version: '3.8'

services:
  nodejs:
    build: .
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5


  nginx:
    image: tiangolo/nginx-rtmp:latest
    volumes:
      - ./rtmp/nginx.conf:/etc/nginx/nginx.conf
      - ./data:/tmp/hls
    ports:
      - "1935:1935"
      - "5050:5050"
    depends_on:
      nodejs:
        condition: service_healthy
